source("https://bioconductor.org/biocLite.R")
biocLite("GOstats")
biocLite("GO.db")
biocLite("impute")
biocLite("preprocessCore")
biocLite("org.Hs.eg.db")
biocLite("GEOquery")
biocLite("limma")

install.packages("rentrez")
install.packages("DGCA")
install.packages("HGNChelper")
install.packages("ggplot2")
install.packages("SuperExactTest")
install.packages("bnlearn")
install.packages("gplots")
install.packages("DBI")
